### ISSUE TITLE
Cannot load https://userstream.twitter.com/1.1/user.json. Response for preflight has invalid HTTP status code 400

### ISSUE THREAD

**Issue by johnRivs** [mileszim/twat#5]
I'm using Chrome. Installed the package via npm and used browserify.

I've followed the instructions and I always get `cannot load https://userstream.twitter.com/1.1/user.json. Response for preflight has invalid HTTP status code 400` 

In fact, I've tried other packages and I get the same error. I can use curl from the command line to consume this endpoint, the one Twitter gives me from their OAuth signature generator. 

Also, right before that message, it shows `OPTIONS https://userstream.twitter.com/1.1/user.json`

Is it because I'm testing locally?

**Comment by mileszim** [comment]
This package was never intended for use with the browser so you're entering into uncharted waters here. The ```Response for preflight has invalid HTTP status code 400``` implies your OPTIONS request is poorly formed and can't negotiate with twitter's CORS settings properly.

After a little googling, it looks like that's your problem: https://twittercommunity.com/t/access-control-allow-origin/7253

Twitter's API, at least the endpoints accessed through twat, don't allow cross-browser requests since they do not have a CORS policy enabled. Only backend for the time being.
